/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package e_commerce_desktop_platform;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Himanshu
 */
public class Collection extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form Collection
     */
    public Collection() {
        initComponents();
        initialize();
        con = JavaDatabase.ConnectToDB();
    }

    private void initialize() {
        setTitle("Collection | DRIP");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setSize(1024, 768);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        updateNoOfProducts = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        addToCartThree = new javax.swing.JButton();
        addToCartTwo = new javax.swing.JButton();
        addToCartOne = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel1.setText("Testimonal");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 120, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel2.setText("About");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart.png"))); // NOI18N
        jLabel3.setText("My Cart");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 110, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jLabel4.setText("Sign out");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 110, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel6.setText("Collection");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 120, -1));

        updateNoOfProducts.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        updateNoOfProducts.setEnabled(false);
        updateNoOfProducts.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                updateNoOfProductsMouseMoved(evt);
            }
        });
        updateNoOfProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateNoOfProductsMouseClicked(evt);
            }
        });
        jPanel2.add(updateNoOfProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 30, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1040, 70));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/collection3.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/collection2.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/collection1.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        addToCartThree.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addToCartThree.setText("Add to cart");
        addToCartThree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addToCartThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartThreeActionPerformed(evt);
            }
        });
        jPanel1.add(addToCartThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 550, 280, 40));

        addToCartTwo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addToCartTwo.setText("Add to cart");
        addToCartTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addToCartTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartTwoActionPerformed(evt);
            }
        });
        jPanel1.add(addToCartTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, 280, 40));

        addToCartOne.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addToCartOne.setText("Add to cart");
        addToCartOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addToCartOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartOneActionPerformed(evt);
            }
        });
        jPanel1.add(addToCartOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 280, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 1040, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
        Testimonal testimonal = new Testimonal();
        testimonal.show();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
        About about = new About();
        about.show();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        dispose();
        My_cart my_cart = new My_cart();
        my_cart.show();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        dispose();
        Sign_in sign_in = new Sign_in();
        sign_in.show();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        dispose();
        Collection collection = new Collection();
        collection.show();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void addToCartOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartOneActionPerformed
        // TODO add your handling code here:
        try {
            String sqlInsert = "INSERT INTO my_cart (Product_Name, Product_Price) VALUES ('Street Jacket','46')";
            pst = con.prepareStatement(sqlInsert);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Item added to cart!");
        } catch (SQLException ex) {
            Logger.getLogger(Collection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addToCartOneActionPerformed

    private void addToCartTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartTwoActionPerformed
        // TODO add your handling code here:
        try {
            String sqlInsert = "INSERT INTO my_cart (Product_Name, Product_Price) VALUES ('Street Sneaker','124')";
            pst = con.prepareStatement(sqlInsert);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Item added to cart!");
        } catch (SQLException ex) {
            Logger.getLogger(Collection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addToCartTwoActionPerformed

    private void addToCartThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartThreeActionPerformed
        // TODO add your handling code here:
        try {
            String sqlInsert = "INSERT INTO my_cart (Product_Name, Product_Price) VALUES ('Street T-Shirt','26')";
            pst = con.prepareStatement(sqlInsert);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Item added to cart!");
        } catch (SQLException ex) {
            Logger.getLogger(Collection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addToCartThreeActionPerformed

    private void updateNoOfProductsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateNoOfProductsMouseMoved
        // TODO add your handling code here:
        try {
            // Fetch the count of items in the database
            String countQuery = "SELECT COUNT(*) FROM my_cart";
            PreparedStatement countStatement = con.prepareStatement(countQuery);
            ResultSet countResult = countStatement.executeQuery();
            countResult.next();
            int itemCount = countResult.getInt(1);

            // Set the count in the JLabel 'noOfProducts'
            updateNoOfProducts.setText(String.valueOf(itemCount));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                // Close resources in the finally block
                if (pst != null) {
                    pst.close();
                }
                if (rs != null) {
                    rs.close();
                }
            } catch (SQLException ex) {
                // Handle exceptions while closing resources if necessary
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_updateNoOfProductsMouseMoved

    private void updateNoOfProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateNoOfProductsMouseClicked
        // TODO add your handling code here:
        dispose();
        My_cart my_cart = new My_cart();
        my_cart.show();
    }//GEN-LAST:event_updateNoOfProductsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Collection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Collection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Collection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Collection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Collection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartOne;
    private javax.swing.JButton addToCartThree;
    private javax.swing.JButton addToCartTwo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel updateNoOfProducts;
    // End of variables declaration//GEN-END:variables
}
