/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package e_commerce_desktop_platform;

import java.awt.*;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Himanshu
 */
public class Forgot_password extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst1;
    PreparedStatement pst2;
    ResultSet rs;

    /**
     * Creates new form Forgot_password
     */
    public Forgot_password() {
        initComponents();
        initialize();
        con = JavaDatabase.ConnectToDB();
    }

    private void initialize() {
        setTitle("Forgot password | DRIP");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setSize(1024, 768);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUsername = new javax.swing.JLabel();
        lbNewPassword = new javax.swing.JLabel();
        pfNewPassword = new javax.swing.JPasswordField();
        lbUserSignIn = new javax.swing.JLabel();
        btnResetPassword = new javax.swing.JButton();
        lbNewConfirmPassword = new javax.swing.JLabel();
        pfNewConfirmPassword = new javax.swing.JPasswordField();
        lbAlreadyHaveAnAccount = new javax.swing.JLabel();
        lbSignIn = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbUsername.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbUsername.setText("Username");
        getContentPane().add(lbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        lbNewPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbNewPassword.setText("New Password");
        getContentPane().add(lbNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        pfNewPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pfNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfNewPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(pfNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 760, 40));

        lbUserSignIn.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbUserSignIn.setText("RESET PASSWORD");
        getContentPane().add(lbUserSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        btnResetPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnResetPassword.setText("RESET");
        btnResetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(btnResetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 760, 40));

        lbNewConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbNewConfirmPassword.setText("New Confirm Password");
        getContentPane().add(lbNewConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        pfNewConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pfNewConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfNewConfirmPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(pfNewConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 760, 40));

        lbAlreadyHaveAnAccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbAlreadyHaveAnAccount.setText("Already have an account?");
        getContentPane().add(lbAlreadyHaveAnAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 670, -1, 20));

        lbSignIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbSignIn.setForeground(new java.awt.Color(51, 51, 255));
        lbSignIn.setText("Sign in");
        lbSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSignInMouseClicked(evt);
            }
        });
        getContentPane().add(lbSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 670, -1, 20));

        tfUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 760, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPasswordActionPerformed
        // TODO add your handling code here:
        try {
            if (tfUsername.getText().isEmpty()
                    || new String(pfNewPassword.getPassword()).isEmpty() || new String(pfNewConfirmPassword.getPassword()).isEmpty()) {
                JOptionPane.showMessageDialog(null, "All fields are required!");
            } else if (!new String(pfNewPassword.getPassword()).equals(new String(pfNewConfirmPassword.getPassword()))) {
                JOptionPane.showMessageDialog(null, "Password and Confirm Password do not match!");
                pfNewPassword.setText("");
                pfNewConfirmPassword.setText("");
                pfNewPassword.requestFocus();
            } else if (tfUsername.getText().length() > 30) {
                JOptionPane.showMessageDialog(null, "Maximum 45 characters are allowed for Username!");
                tfUsername.setText("");
                tfUsername.requestFocus();
            } else if (new String(pfNewPassword.getPassword()).length() > 30) {
                JOptionPane.showMessageDialog(null, "Maximum 45 characters are allowed for Password!");
                pfNewPassword.setText("");
                pfNewConfirmPassword.setText("");
                pfNewPassword.requestFocus();
            } else {
                // UpdateIntoSignup
                String sqlInsertIntoSignup = "UPDATE sign_up SET Password = ? WHERE Username = ?";
                pst1 = con.prepareStatement(sqlInsertIntoSignup);
                pst1.setString(1, new String(pfNewPassword.getPassword()));
                pst1.setString(2, tfUsername.getText());
                pst1.executeUpdate();
                JOptionPane.showMessageDialog(null, "Successfully updated new password!\nNow you can sign in");

                // UpdateIntoSignin
                String sqlInsertIntoSignin = "UPDATE sign_in SET Password = ? WHERE Username = ?";
                pst2 = con.prepareStatement(sqlInsertIntoSignin);
                pst2.setString(1, new String(pfNewPassword.getPassword()));
                pst2.setString(2, tfUsername.getText());
                pst2.executeUpdate();

                // Resetting fields to blank/empty
                tfUsername.setText("");
                pfNewPassword.setText("");
                pfNewConfirmPassword.setText("");
                tfUsername.requestFocus();
            }

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnResetPasswordActionPerformed

    private void pfNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfNewPasswordActionPerformed

    private void pfNewConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfNewConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfNewConfirmPasswordActionPerformed

    private void lbSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSignInMouseClicked
        // TODO add your handling code here:
        dispose();
        Sign_in signIn = new Sign_in();
        signIn.show();
    }//GEN-LAST:event_lbSignInMouseClicked

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgot_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResetPassword;
    private javax.swing.JLabel lbAlreadyHaveAnAccount;
    private javax.swing.JLabel lbNewConfirmPassword;
    private javax.swing.JLabel lbNewPassword;
    private javax.swing.JLabel lbSignIn;
    private javax.swing.JLabel lbUserSignIn;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPasswordField pfNewConfirmPassword;
    private javax.swing.JPasswordField pfNewPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
