/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package e_commerce_desktop_platform;

import java.awt.*;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Himanshu
 */
public class Sign_up extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst1;
    PreparedStatement pst2;
    ResultSet rs;

    /**
     * Creates new form Sign_up
     */
    public Sign_up() {
        initComponents();
        initialize();
        con = JavaDatabase.ConnectToDB();
    }

    private void initialize() {
        setTitle("Sign up | DRIP");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setSize(1024, 768);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUserSignIn = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lbUsername = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        lbPassword = new javax.swing.JLabel();
        pfPassword = new javax.swing.JPasswordField();
        lbConfirmPassword = new javax.swing.JLabel();
        pfConfirmPassword = new javax.swing.JPasswordField();
        btnSignuP = new javax.swing.JButton();
        lbAlreadyHaveAnAccount = new javax.swing.JLabel();
        lbSignIn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbUserSignIn.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbUserSignIn.setText("USER SIGN UP");
        getContentPane().add(lbUserSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        lbName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbName.setText("Name");
        getContentPane().add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        tfName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 760, 40));

        lbEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbEmail.setText("Email");
        getContentPane().add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        tfEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 760, 40));

        lbUsername.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbUsername.setText("Username");
        getContentPane().add(lbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        tfUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 760, 40));

        lbPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbPassword.setText("Password");
        getContentPane().add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, -1));

        pfPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(pfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 760, 40));

        lbConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbConfirmPassword.setText("Confirm Password");
        getContentPane().add(lbConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, -1, -1));

        pfConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(pfConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 760, 40));

        btnSignuP.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSignuP.setText("SIGN UP");
        btnSignuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignuPActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignuP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, 760, 40));

        lbAlreadyHaveAnAccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbAlreadyHaveAnAccount.setText("Already have an account?");
        getContentPane().add(lbAlreadyHaveAnAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 670, -1, 20));

        lbSignIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbSignIn.setForeground(new java.awt.Color(51, 51, 255));
        lbSignIn.setText("Sign in");
        lbSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSignInMouseClicked(evt);
            }
        });
        getContentPane().add(lbSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 670, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignuPActionPerformed
        // TODO add your handling code here:
        try {
            if (tfName.getText().isEmpty() || tfEmail.getText().isEmpty() || tfUsername.getText().isEmpty()
                    || new String(pfPassword.getPassword()).isEmpty() || new String(pfConfirmPassword.getPassword()).isEmpty()) {
                JOptionPane.showMessageDialog(null, "All fields are required!");
            } else if (!new String(pfPassword.getPassword()).equals(new String(pfConfirmPassword.getPassword()))) {
                JOptionPane.showMessageDialog(null, "Password and Confirm Password do not match!");
                pfPassword.setText("");
                pfConfirmPassword.setText("");
                pfPassword.requestFocus();
            } else if (tfName.getText().length() > 30) {
                JOptionPane.showMessageDialog(null, "Maximum 45 characters are allowed for Name!");
                tfName.setText("");
                tfName.requestFocus();
            } else if (tfEmail.getText().length() > 30) {
                JOptionPane.showMessageDialog(null, "Maximum 45 characters are allowed for Email!");
                tfEmail.setText("");
                tfEmail.requestFocus();
            } else if (tfUsername.getText().length() > 30) {
                JOptionPane.showMessageDialog(null, "Maximum 45 characters are allowed for Username!");
                tfUsername.setText("");
                tfUsername.requestFocus();
            } else if (new String(pfPassword.getPassword()).length() > 30) {
                JOptionPane.showMessageDialog(null, "Maximum 45 characters are allowed for Password!");
                pfPassword.setText("");
                pfConfirmPassword.setText("");
                pfPassword.requestFocus();
            } else {
                String sqlCheck = "SELECT COUNT(*) FROM sign_up WHERE Username = ?";
                pst1 = con.prepareStatement(sqlCheck);
                pst1.setString(1, tfUsername.getText());
                ResultSet rs = pst1.executeQuery();
                rs.next();
                int count = rs.getInt(1);
                if (count > 0) {
                    JOptionPane.showMessageDialog(null, "Username already exists! Please choose a different username.");
                    tfUsername.setText("");
                    tfUsername.requestFocus();
                } else {
                    // InsertIntoSignup
                    String sqlInsert = "INSERT INTO sign_up (Name, Email, Username, Password) VALUES (?, ?, ?, ?)";
                    pst1 = con.prepareStatement(sqlInsert);
                    pst1.setString(1, tfName.getText());
                    pst1.setString(2, tfEmail.getText());
                    pst1.setString(3, tfUsername.getText());
                    pst1.setString(4, new String(pfPassword.getPassword()));
                    pst1.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Successfully created a new account!");

                    // InsertIntoSignin
                    String sqlInsertIntoSignin = "INSERT INTO sign_in (Username, Password) VALUES (?, ?)";
                    pst2 = con.prepareStatement(sqlInsertIntoSignin);
                    pst2.setString(1, tfUsername.getText());
                    pst2.setString(2, new String(pfPassword.getPassword()));
                    pst2.executeUpdate();

                    // Resetting fields to blank/empty
                    tfName.setText("");
                    tfEmail.setText("");
                    tfUsername.setText("");
                    pfPassword.setText("");
                    pfConfirmPassword.setText("");
                    tfName.requestFocus();
                }
            }

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btnSignuPActionPerformed

    private void lbSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSignInMouseClicked
        // TODO add your handling code here:
        dispose();
        Sign_in signIn = new Sign_in();
        signIn.show();
    }//GEN-LAST:event_lbSignInMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignuP;
    private javax.swing.JLabel lbAlreadyHaveAnAccount;
    private javax.swing.JLabel lbConfirmPassword;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbSignIn;
    private javax.swing.JLabel lbUserSignIn;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPasswordField pfConfirmPassword;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfName;
    public javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
