/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package e_commerce_desktop_platform;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Himanshu
 */
public class Sign_in extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form Sign_In
     */
    public Sign_in() {
        initComponents();
        initialize();
        con = JavaDatabase.ConnectToDB();
    }

    private void initialize() {
        setTitle("Sign in | DRIP");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setSize(1024, 768);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUserSignIn = new javax.swing.JLabel();
        lbUsername = new javax.swing.JLabel();
        pfPassword = new javax.swing.JPasswordField();
        tfUsername = new javax.swing.JTextField();
        lbPassword = new javax.swing.JLabel();
        lbForgotPassword = new javax.swing.JLabel();
        btnSignIn = new javax.swing.JButton();
        lbDontHaveAnAccount = new javax.swing.JLabel();
        lbCreateNewOne = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(480, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbUserSignIn.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbUserSignIn.setText("USER LOGIN");
        getContentPane().add(lbUserSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        lbUsername.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbUsername.setText("Username");
        getContentPane().add(lbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        pfPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(pfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 780, 40));

        tfUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 780, 40));

        lbPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbPassword.setText("Password");
        getContentPane().add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        lbForgotPassword.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lbForgotPassword.setText("Forgot Password?");
        lbForgotPassword.setToolTipText("");
        lbForgotPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbForgotPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(lbForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 140, -1));

        btnSignIn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSignIn.setText("SIGN IN");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 780, 60));

        lbDontHaveAnAccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbDontHaveAnAccount.setText("Don't have an account?");
        getContentPane().add(lbDontHaveAnAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, -1, -1));

        lbCreateNewOne.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbCreateNewOne.setForeground(new java.awt.Color(51, 51, 255));
        lbCreateNewOne.setText("Create One Now");
        lbCreateNewOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCreateNewOneMouseClicked(evt);
            }
        });
        getContentPane().add(lbCreateNewOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbForgotPasswordMouseClicked
        // TODO add your handling code here:
        dispose();
        Forgot_password forgotPassword = new Forgot_password();
        forgotPassword.show();
    }//GEN-LAST:event_lbForgotPasswordMouseClicked

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM sign_in WHERE Username = ? AND Password = ?";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, tfUsername.getText());
            pst.setString(2, new String(pfPassword.getPassword()));
            rs = pst.executeQuery();
            JOptionPane.showMessageDialog(null, "Sign in successful!");
            if (rs.next()) {
                rs.close();
                pst.close();
                dispose(); // Close the current JFrame
                About about = new About();
                about.show();
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect Username & Password!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pst != null) {
                    pst.close();
                }
            } catch (SQLException e) {
                // Handle the exception if needed
            }
        }
    }//GEN-LAST:event_btnSignInActionPerformed

    private void lbCreateNewOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCreateNewOneMouseClicked
        // TODO add your handling code here:
        dispose();
        Sign_up signUp = new Sign_up();
        signUp.show();
    }//GEN-LAST:event_lbCreateNewOneMouseClicked

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void pfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignIn;
    private javax.swing.JLabel lbCreateNewOne;
    private javax.swing.JLabel lbDontHaveAnAccount;
    private javax.swing.JLabel lbForgotPassword;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbUserSignIn;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
